name: Build AWS Lambda Ruby images for Ruby 3.4

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron:  '30 6 * * MON-FRI'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  packages: write

jobs:
  ruby-dev-images:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image: [aws-lambda-ruby-dev, aws-lambda-ruby-postgres]
    name: Build ci/${{ matrix.image }}:3.4
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        if: hashFiles(format('ci/{0}/3.4/get-dependencies.sh', matrix.image)) != ''
        with:
          role-to-assume: ${{ vars.LINUX_LAYER_ROLE_ARN_SANDBOX }}
          role-duration-seconds: 1800
          aws-region: eu-west-1
      - name: Get image dependencies
        run: ./get-dependencies.sh
        if: hashFiles(format('ci/{0}/3.4/get-dependencies.sh', matrix.image)) != ''
        working-directory: ci/${{ matrix.image }}/3.4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image
        uses: docker/build-push-action@v5
        with:
          context: ci/${{ matrix.image }}/3.4
          pull: true
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ghcr.io/${{ github.repository }}/ci/${{ matrix.image }}:3.4
  ruby-local-images:
    runs-on: ubuntu-latest
    needs: ruby-dev-images
    strategy:
      fail-fast: false
      matrix:
        image: [aws-lambda-ruby-dev, aws-lambda-ruby-postgres]
    name: Build local-dev/${{ matrix.image }}:3.4
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image
        uses: docker/build-push-action@v5
        with:
          context: local-dev/${{ matrix.image }}/3.4
          pull: true
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ghcr.io/${{ github.repository }}/local-dev/${{ matrix.image }}:3.4
